stages:
#    - build
    - deploy

pages:
    stage: deploy
    before_script:
        - gem install jekyll
        - gem install jekyll-paginate
        - gem install jekyll-gist
    script:
        - jekyll build -d public
    artifacts:
        paths:
            - public
    only:
        - master
