# Permalinks
permalink:           pretty

# Setup
title:               The Short, Tampered Clavier
tagline:             A Fugue in C++
#url:                "http://theshorttamperedclavier.github.io"
baseurl:             ""
paginate:            5
exclude: ['README.md']

# About/contact
authors:
  names:             Aalok Sathe, Mandar Juvekar, Shardul Chiplunkar

# Custom vars
github:
  repo:              https://github.com/theshorttamperedclavier/theshorttamperedclavier.github.io
excerpt-words:       100

# Staticman configuration
repository: "theshorttamperedclavier/theshorttamperedclavier.github.io"

staticman:
    branch: "master"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
